version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "y-iihoshi"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "y-iihoshi"
  - package-ecosystem: "pip"
    directory: "/ManualGenerator"
    schedule:
      interval: "monthly"
    reviewers:
      - "y-iihoshi"
