//-----------------------------------------------------------------------
// <copyright file="ReimuPluginGenerator.cs" company="None">
// Copyright (c) IIHOSHI Yoshinori.
// Licensed under the BSD-2-Clause license. See LICENSE.txt file in the project root for full license information.
// </copyright>
//-----------------------------------------------------------------------

namespace ReimuPlugins.SourceGenerator;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ReimuPlugins.Common;

[Generator]
public class ReimuPluginGenerator : IIncrementalGenerator
{
    private static readonly string NamespaceName = typeof(ReimuPluginGenerator).Namespace;
    private static readonly string AttributeName = "ReimuPluginAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(EmitAttribute);

        var source = context.SyntaxProvider.ForAttributeWithMetadataName(
            $"{NamespaceName}.{AttributeName}",
            predicate: static (node, token) => node is ClassDeclarationSyntax,
            transform: static (ctx, token) => ctx);

        context.RegisterSourceOutput(source, Emit);
    }

    private static void EmitAttribute(IncrementalGeneratorPostInitializationContext context)
    {
        var attributeSource = $$"""
            // <auto-generated/>

            using System;

            namespace {{NamespaceName}};

            [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
            internal sealed class {{AttributeName}} : Attribute;
            """;

        context.AddSource("ReimuPluginAttribute.g.cs", attributeSource);
    }

    private static void Emit(SourceProductionContext context, GeneratorAttributeSyntaxContext source)
    {
        if (source.TargetSymbol is not INamedTypeSymbol symbol)
        {
            return;
        }

        if (!symbol.AllInterfaces.Any(static intf => intf.Name is nameof(IReimuPluginRev1) or nameof(IReimuPluginRev2)))
        {
            return;
        }

        var nativeGetFileInfoText1 = symbol.GetMembers(nameof(IReimuPluginRev1.GetFileInfoText1)).IsEmpty
            ? """
                // GetFileInfoText1 is not implemented.
            """
            : """
                [DllExport(callingConvention: CallingConvention.StdCall)]
                public static ErrorCode GetFileInfoText1(IntPtr src, uint size, out IntPtr dst)
                {
                    return Impl.GetFileInfoText1(src, size, out dst);
                }
            """;

        var nativeGetFileInfoText2 = symbol.GetMembers(nameof(IReimuPluginRev1.GetFileInfoText2)).IsEmpty
            ? """
                // GetFileInfoText2 is not implemented.
            """
            : """
                [DllExport(callingConvention: CallingConvention.StdCall)]
                public static ErrorCode GetFileInfoText2(IntPtr src, uint size, out IntPtr dst)
                {
                    return Impl.GetFileInfoText2(src, size, out dst);
                }
            """;

        var nativeGetFileInfoImage1 = symbol.GetMembers(nameof(IReimuPluginRev2.GetFileInfoImage1)).IsEmpty
            ? """
                // GetFileInfoImage1 is not implemented.
            """
            : """
                [DllExport(callingConvention: CallingConvention.StdCall)]
                public static ErrorCode GetFileInfoImage1(IntPtr src, uint size, out IntPtr dst, out IntPtr info)
                {
                    return Impl.GetFileInfoImage1(src, size, out dst, out info);
                }
            """;

        var nativeGetFileInfoImage2 = symbol.GetMembers(nameof(IReimuPluginRev2.GetFileInfoImage2)).IsEmpty
            ? """
                // GetFileInfoImage2 is not implemented.
            """
            : """
                [DllExport(callingConvention: CallingConvention.StdCall)]
                public static ErrorCode GetFileInfoImage2(IntPtr src, uint size, out IntPtr dst, out IntPtr info)
                {
                    return Impl.GetFileInfoImage2(src, size, out dst, out info);
                }
            """;

        var nativeEditDialog = symbol.GetMembers(nameof(IReimuPluginRev1.EditDialog)).IsEmpty
            ? """
                // EditDialog is not implemented.
            """
            : """
                [DllExport(callingConvention: CallingConvention.StdCall)]
                public static ErrorCode EditDialog(IntPtr parent, string file)
                {
                    return Impl.EditDialog(parent, file);
                }
            """;

        var nativeConfigDialog = symbol.GetMembers(nameof(IReimuPluginRev1.ConfigDialog)).IsEmpty
            ? """
                // ConfigDialog is not implemented.
            """
            : """
                [DllExport(callingConvention: CallingConvention.StdCall)]
                public static ErrorCode ConfigDialog(IntPtr parent)
                {
                    return Impl.ConfigDialog(parent);
                }
            """;

        var nativeSource = $$"""
            // <auto-generated/>

            namespace {{symbol.ContainingNamespace}};

            using System;
            using System.Runtime.InteropServices;
            using NXPorts.Attributes;
            using ReimuPlugins.Common;

            public static class {{symbol.Name}}Native
            {
                private static readonly {{symbol.Name}} Impl = new();

                [DllExport(callingConvention: CallingConvention.StdCall)]
                public static Revision GetPluginRevision()
                {
                    return Impl.GetPluginRevision();
                }

                [DllExport(callingConvention: CallingConvention.StdCall)]
                public static int GetPluginInfo(int index, IntPtr info, uint size)
                {
                    return Impl.GetPluginInfo(index, info, size);
                }

                [DllExport(callingConvention: CallingConvention.StdCall)]
                public static ErrorCode GetColumnInfo(out IntPtr info)
                {
                    return Impl.GetColumnInfo(out info);
                }

                [DllExport(callingConvention: CallingConvention.StdCall)]
                public static uint IsSupported(IntPtr src, uint size)
                {
                    return Impl.IsSupported(src, size);
                }

                [DllExport(callingConvention: CallingConvention.StdCall)]
                public static ErrorCode GetFileInfoList(IntPtr src, uint size, out IntPtr info)
                {
                    return Impl.GetFileInfoList(src, size, out info);
                }

            {{nativeGetFileInfoText1}}

            {{nativeGetFileInfoText2}}

            {{nativeGetFileInfoImage1}}

            {{nativeGetFileInfoImage2}}

            {{nativeEditDialog}}

            {{nativeConfigDialog}}
            }
            """;

        context.AddSource($"{symbol.Name}Native.g.cs", nativeSource);
    }
}
