name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2022

    strategy:
      matrix:
        configuration: [Debug, Release]
        target-framework: [net48]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
        cache-dependency-path: 'ManualGenerator/requirements.txt'

    - name: Restore Python packages
      run: |
        python -m pip install -U pip
        python -m pip install -r ManualGenerator/requirements.txt

    - name: Cache NuGet packages
      uses: actions/cache@v3.3.0
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ matrix.target-framework }}-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-${{ matrix.target-framework }}-
          ${{ runner.os }}-nuget-

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3

    - name: Build
      run: >
        msbuild REIMU_Plugins_V2.sln /m /restore /verbosity:minimal
        /p:Configuration=${{ matrix.configuration }}
        /p:TargetFrameworks=${{ matrix.target-framework }}

    - name: Run FOSSA scan and upload build data
      env:
        FOSSA_API_KEY: 546ea14e5b1c4a901201f2d1cfc44a83   # Push only API token
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.ps1'))
        fossa analyze
        fossa test
      if: matrix.configuration == 'Debug'

    - name: Collect artifacts
      run: CollectArtifacts.bat ${{ matrix.configuration }} ${{ matrix.target-framework }}
      shell: cmd
      if: matrix.configuration == 'Release'

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: threplay_rpi.${{ matrix.target-framework }}
        path: publish\${{ matrix.target-framework }}
      if: matrix.configuration == 'Release'
