name: CI

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v*'
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        target-framework: [net48]

    uses: ./.github/workflows/_build.yml
    with:
      python-version: '3.x'
      dotnet-configuration: ${{ matrix.configuration }}
      dotnet-target-framework: ${{ matrix.target-framework }}
      artifact-name: 'threplay_rpi.${{ matrix.configuration }}.${{ matrix.target-framework }}'
