name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      python-version: '3.x'
      dotnet-configuration: 'Release'
      dotnet-target-framework: 'net48'
      artifact-name: 'threplay_rpi-${{ github.ref_name }}'

  release:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: 'threplay_rpi-${{ github.ref_name }}'
          path: artifact
      - name: Zip artifact
        run: 7z a threplay_rpi-${{ github.ref_name }}.zip -r ./artifact/*
      - name: Create GitHub release as draft
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          draft: true
          files: 'threplay_rpi-${{ github.ref_name }}.zip'
